version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  app:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - qdrant
    volumes:
      - .:/app
    command: sh -c "ollama serve & jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root" 